kubectl delete gw --all;
kubectl delete vs --all;
kubectl delete dr --all;
kubectl delete requestauthentication request-jwt -n istio-system;
kubectl delete authorizationpolicy frontend-ingress -n istio-system;
sleep 0.01;
kubectl apply -f modifiedyamls/bookinfo/enforce-mtls.yaml;
kubectl apply -f modifiedyamls/bookinfo/routing-rules.yaml;
kubectl apply -f modifiedyamls/bookinfo/request-authentication-jwt.yaml;
kubectl apply -f modifiedyamls/bookinfo/denypolicy-response-without-token.yaml;
